config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home' => 'pages#home'

  resources :tour_sessions
  resources :tours
  resources :breweries
  resources :bookings
  resources :charges

  get "/app" => 'pages#app'

end

app/models/tour_session.rb
# == Schema Information
#
# Table name: tour_sessions
#
#  id            :integer          not null, primary key
#  tour_date     :datetime
#  tour_id       :integer
#  number_booked :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class TourSession < ActiveRecord::Base
  has_many :bookings, dependent: :destroy
  belongs_to :tour
end

app/controllers/tour_sessions_controller.rb
class TourSessionsController < ApplicationController
  before_action :set_tour_session, only: [:show, :edit, :update, :destroy]

  # GET /tour_sessions
  # GET /tour_sessions.json
  def index
    @tour_sessions = TourSession.all
  end

  # GET /tour_sessions/1
  # GET /tour_sessions/1.json
  def show
  end

  # GET /tour_sessions/new
  def new
    @tour_session = TourSession.new
  end

  # GET /tour_sessions/1/edit
  def edit
  end

  # POST /tour_sessions
  # POST /tour_sessions.json
  def create
    @tour_session = TourSession.new(tour_session_params)

    respond_to do |format|
      if @tour_session.save
        format.html { redirect_to @tour_session, notice: 'Tour session was successfully created.' }
        format.json { render :show, status: :created, location: @tour_session }
      else
        format.html { render :new }
        format.json { render json: @tour_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tour_sessions/1
  # PATCH/PUT /tour_sessions/1.json
  def update
    respond_to do |format|
      if @tour_session.update(tour_session_params)
        format.html { redirect_to @tour_session, notice: 'Tour session was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour_session }
      else
        format.html { render :edit }
        format.json { render json: @tour_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_sessions/1
  # DELETE /tour_sessions/1.json
  def destroy
    @tour_session.destroy
    respond_to do |format|
      format.html { redirect_to tour_sessions_url, notice: 'Tour session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour_session
      @tour_session = TourSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_session_params
      params.require(:tour_session).permit(:tour_date, :tour_id, :number_booked)
    end
end

app/helpers/tour_sessions_helper.rb
module TourSessionsHelper
end

app/views/tour_sessions/_form.html.erb
<%= form_for(@tour_session) do |f| %>
  <% if @tour_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour_session.errors.count, "error") %> prohibited this tour_session from being saved:</h2>

      <ul>
      <% @tour_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tour_date %><br>
    <%= f.datetime_select :tour_date %>
  </div>
  <div class="field">
    <%= f.label :tour_id %><br>
    <%= f.number_field :tour_id %>
  </div>
  <div class="field">
    <%= f.label :number_booked %><br>
    <%= f.number_field :number_booked %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tour_sessions/edit.html.erb
<h1>Editing Tour Session</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour_session %> |
<%= link_to 'Back', tour_sessions_path %>

app/views/tour_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tour Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Tour date</th>
      <th>Tour</th>
      <th>Number booked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tour_sessions.each do |tour_session| %>
      <tr>
        <td><%= tour_session.tour_date %></td>
        <td><%= tour_session.tour_id %></td>
        <td><%= tour_session.number_booked %></td>
        <td><%= link_to 'Show', tour_session %></td>
        <td><%= link_to 'Edit', edit_tour_session_path(tour_session) %></td>
        <td><%= link_to 'Destroy', tour_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour session', new_tour_session_path %>

app/views/tour_sessions/new.html.erb
<h1>New Tour Session</h1>

<%= render 'form' %>

<%= link_to 'Back', tour_sessions_path %>

app/views/tour_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tour date:</strong>
  <%= @tour_session.tour_date %>
</p>

<p>
  <strong>Tour:</strong>
  <%= @tour_session.tour_id %>
</p>

<p>
  <strong>Number booked:</strong>
  <%= @tour_session.number_booked %>
</p>

<%= link_to 'Edit', edit_tour_session_path(@tour_session) %> |
<%= link_to 'Back', tour_sessions_path %>