config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home' => 'pages#home'

  resources :tour_sessions
  resources :tours
  resources :breweries
  resources :bookings
  resources :charges

  get "/app" => 'pages#app'

end

app/models/booking.rb
# == Schema Information
#
# Table name: bookings
#
#  id            :integer          not null, primary key
#  name_last     :string
#  name_first    :string
#  date          :datetime
#  session_id    :integer
#  number_people :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Booking < ActiveRecord::Base
  belongs_to :tour_session
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    flash[:booking_id] = @booking.id
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    # Amount in cents

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Please make a payment to confirm your booking.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:name_last, :name_first, :date, :session_id, :number_people)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name_last %>
    <%= f.text_field :name_last, :required => true %>
  </div>
  <br>
  <div class="field">
    <%= f.label :name_first %>
    <%= f.text_field :name_first, :required => true %>
  </div>
  <br>
  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date, :required => true%>
  </div>
  <br>
  <!-- <div class="field">
    <%#= f.label :session_id %><br>
    <%#= f.number_field :tour_session_id %>
  </div> -->
  <div class="field">
    <%= f.label :number_people %>
    <%= f.number_field :number_people, :required => true %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Name last</th>
      <th>Name first</th>
      <th>Date</th>
      <th>Session</th>
      <th>Number people</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.name_last %></td>
        <td><%= booking.name_first %></td>
        <td><%= booking.date %></td>
        <td><%= booking.tour_session_id %></td>
        <td><%= booking.number_people %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<div class="wrapper">
  <div class="main">
    <h1>New Booking</h1>
    <%= render 'form' %>
    <%= link_to 'Back', bookings_path %>
  </div>
</div>
 <!-- <img id="h" src="/assets/hop.png" alt="" style="position:absolute; top:20px; left:20px"> -->
 <%= image_tag("hop.png", :id => "h", :style => "position:absolute; top:20px; left:20px;") %>


<footer class="footer">
  <div id="container">
    <div id="top">
    <div class="beer-foam">
    <div class="foam-1"></div>
    <div class="foam-2"></div>
    <div class="foam-3"></div>
    <div class="foam-4"></div>
    <div class="foam-5"></div>
    <div class="foam-6"></div>
    <div class="foam-7"></div>
    <div class="foam-8"></div>
    <div class="foam-9"></div>
    <div class="foam-10"></div>
    <div class="foam-11"></div>
    <div class="foam-12"></div>
    <div class="foam-13"></div>
    <div class="foam-14"></div>
    <div class="foam-15"></div>
    </div>
    <div id="liquid">
    <div class="bubble bubble1"></div>
    <div class="bubble bubble2"></div>
    <div class="bubble bubble3"></div>
    <div class="bubble bubble4"></div>
    <div class="bubble bubble5"></div>
    </div>
    </div>
    </div>
</footer>

app/views/bookings/show.html.erb
<div class="main">
    <div class="wrapper">

        <!-- <p id="notice"><%= notice %></p> -->

        <% if !@booking.confirmed %>
        <h1>
            Your booking will not be confirmed until you have paid, biyatch!</h1>
        <%= form_tag charges_path do %>
        <article>
            <% if flash[:error].present? %>
            <div id="error_explanation">
                <p><%= flash[:error] %></p>
            </div>
            <% end %>

            <label class="amount">
                <span>Amount: $100.00</span>
            </label>
        </article>

        <script
            src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Crafty Beer Tours"
            data-amount="10000"
            data-locale="auto"
            data-image="<%= image_path("bearwink.jpg") %>">
            </script>


        <% end %>
        <% end %>

        <p>
            <strong>Last Name:</strong>
            <%= @booking.name_last %>
        </p>

        <p>
            <strong>First Name:</strong>
            <%= @booking.name_first %>
        </p>

        <p>
            <strong>Date:</strong>
            <%= @booking.date %>
        </p>

        <!-- <p>
      <strong>Session:</strong>
      <%#= @booking.tour_session_id %>
    </p> -->

        <p>
            <strong>Number people:</strong>
            <%= @booking.number_people %>
        </p>

        <%= link_to 'Edit', edit_booking_path(@booking) %>
        |
        <%= link_to 'Back', bookings_path %>

    </div>
</div>

<footer class="footer">
    <div id="container">
        <div id="top">
            <div class="beer-foam">
                <div class="foam-1"></div>
                <div class="foam-2"></div>
                <div class="foam-3"></div>
                <div class="foam-4"></div>
                <div class="foam-5"></div>
                <div class="foam-6"></div>
                <div class="foam-7"></div>
                <div class="foam-8"></div>
                <div class="foam-9"></div>
                <div class="foam-10"></div>
                <div class="foam-11"></div>
                <div class="foam-12"></div>
                <div class="foam-13"></div>
                <div class="foam-14"></div>
                <div class="foam-15"></div>
            </div>
            <div id="liquid">
                <div class="bubble bubble1"></div>
                <div class="bubble bubble2"></div>
                <div class="bubble bubble3"></div>
                <div class="bubble bubble4"></div>
                <div class="bubble bubble5"></div>
            </div>
        </div>
    </div>
</footer>