config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home' => 'pages#home'

  resources :tour_sessions
  resources :tours
  resources :breweries
  resources :bookings
  resources :charges

  get "/app" => 'pages#app'

end

app/models/tour.rb
# == Schema Information
#
# Table name: tours
#
#  id           :integer          not null, primary key
#  tour_name    :string
#  price        :float
#  num_capacity :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Tour < ActiveRecord::Base
  has_many :tour_sessions, dependent: :destroy
  has_and_belongs_to_many :breweries
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :set_tour, only: [:show, :edit, :update, :destroy]

  # GET /tours
  # GET /tours.json
  def index
    @tours = Tour.all
  end

  # GET /tours/1
  # GET /tours/1.json
  def show
    @hash = Gmaps4rails.build_markers(@tour.breweries) do |brewery, marker|
      marker.lat brewery.latitude
      marker.lng brewery.longitude
      marker.picture({
      :picture => view_context.image_path('beer11.png'),
      :width => 32,
      :height => 32
      })
      marker.infowindow render_to_string( :partial => 'infowindow', locals:{ brewery: brewery } )
   end
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create
    @tour = Tour.new(tour_params)

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update
    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:tour_name, :price, :num_capacity)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_form.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tour_name %><br>
    <%= f.text_field :tour_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :num_capacity %><br>
    <%= f.number_field :num_capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tours/_infowindow.html.erb
<h2><%= brewery.brewery_name %></h2>
<%=image_tag(brewery.image, :class => "brewpics") %>
<p><%= brewery.description %></p>
<p>website <%=brewery.website%></p>

app/views/tours/_map.html.erb
<div id="map-container">
    <div id="map"></div>
</div>

<script type="text/javascript">

    var handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });

 </script>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form' %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tours</h1>

<table>
  <thead>
    <tr>
      <th>Tour name</th>
      <th>Price</th>
      <th>Num capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tours.each do |tour| %>
      <tr>
        <td><%= tour.tour_name %></td>
        <td><%= tour.price %></td>
        <td><%= tour.num_capacity %></td>
        <td><%= link_to 'Show', tour %></td>
        <td><%= link_to 'Edit', edit_tour_path(tour) %></td>
        <td><%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tour', new_tour_path %>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form' %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tour name:</strong>
  <%= @tour.tour_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tour.price %>
</p>

<p>
  <strong>Num capacity:</strong>
  <%= @tour.num_capacity %>
</p>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>

<%= render 'map' %>