config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/home' => 'pages#home'

  resources :tour_sessions
  resources :tours
  resources :breweries
  resources :bookings
  resources :charges

  get "/app" => 'pages#app'

end

app/models/brewery.rb
# == Schema Information
#
# Table name: breweries
#
#  id           :integer          not null, primary key
#  brewery_name :string
#  address      :string
#  longitude    :float
#  latitude     :float
#  image        :string
#  description  :text
#  website      :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Brewery < ActiveRecord::Base
  has_and_belongs_to_many :tours
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?




end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
    @hash = Gmaps4rails.build_markers(@breweries) do |brewery, marker|
      marker.lat brewery.latitude
      marker.lng brewery.longitude
      marker.infowindow render_to_string( :partial => 'infowindow', locals:{ brewery: brewery } )
   end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:brewery_name, :address, :long, :lat, :image, :description, :website)
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brewery_name %><br>
    <%= f.text_field :brewery_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breweries</h1>

<table>
  <thead>
    <tr>
      <th>Brewery name</th>
      <th>Address</th>
      <th>Longitude</th>
      <th>Latitude</th>
      <th>Image</th>
      <th>Description</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breweries.each do |brewery| %>
      <tr>
        <td><%= brewery.brewery_name %></td>
        <td><%= brewery.address %></td>
        <td><%= brewery.longitude %></td>
        <td><%= brewery.latitude %></td>
        <td><%= image_tag(brewery.image, :class => "brewpics") %></td>
        <td><%= brewery.description %></td>
        <td><%= brewery.website %></td>
        <td><%= link_to 'Show', brewery %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brewery', new_brewery_path %>

<%= render 'map' %>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brewery name:</strong>
  <%= @brewery.brewery_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @brewery.address %>
</p>

<p>
  <strong>Long:</strong>
  <%= @brewery.longitude %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @brewery.latitude %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@brewery.image)%>
</p>

<p>
  <strong>Description:</strong>
  <%= @brewery.description %>
</p>

<p>
  <strong>Website:</strong>
  <%= @brewery.website %>
</p>

<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>

<div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handles.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>